### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by monksoul** [TerryZ/SelectMenu#1]
非常感谢您提供的诸多非常好用的插件，`SelectPage`目前已经成为我们ERP后台的标配，我相信`SelectMenu`也一样是我们所喜爱。就目前的功能提一个小建议：

- SelectMenu位置自动调整，根据边缘可视区调整。

最后非常感谢您提供这么好的插件。

**Comment by TerryZ** [comment]
这个功能是开发计划中的项目，且基本已经完成，下个版本就会更新

它会和SelectPage一样，自动调整列表的位置

**Comment by TerryZ** [comment]
v2.0版本上已经增加了该功能，谢谢
