### ISSUE TITLE
搜索输入 前/后 列表框位置变化（屏幕分辨率：1366x768px）

### ISSUE THREAD

**Issue by fulicat** [TerryZ/SelectMenu#12]
![-2](https://user-images.githubusercontent.com/723907/34656943-09733190-f45c-11e7-99d1-4105c3c3856b.jpg)

**Comment by TerryZ** [comment]
输入前，菜单自动向上展开是因为下方的区域不足以展开菜单，照你的截图看，你这种是管理平台的内容区域，这种区域不知道是不是使用 `iframe` 做的，如果是，需要观察 `iframe` 的实际可用高度

而输入后，内容条数不多，菜单高度变小，就够向下展开了

这是菜单的自动边缘判断的功能

**Comment by fulicat** [comment]
我们的系统这里没有采用iframe, 应该是你增加的新特性，屏幕边缘自动判断的特性。

我是想固定在下方向，或者 可以选择 开/关 边缘自动判断的配置参数项？

**Comment by TerryZ** [comment]
目前是自动的，没有设置开关
