### ISSUE TITLE
插件主页链接有误

### ISSUE THREAD

**Issue by monksoul** [TerryZ/SelectMenu#2]
插件主页地址：

- [https://terryz.github.io/selectmenu/index.html](https://terryz.github.io/selectmenu/index.html) 

- [https://terryz.oschina.io/selectmenu/index.html](https://terryz.oschina.io/selectmenu/index.html) 

页面顶部`右上角` 的 `View on Github` 链接有误，目前指向了 `SelectPage` 仓库地址。

**Comment by TerryZ** [comment]
太粗心，链接错了，感谢指出！

已经修正了
