### ISSUE TITLE
对高级菜单的建议

### ISSUE THREAD

**Issue by ZeroScorpion** [TerryZ/SelectMenu#5]
对于高级菜单的多tab，在选择不同tab中的数据时，建议能提供清除别的tab中选中的功能O(∩_∩)O~

**Comment by TerryZ** [comment]
你的需求提得比较奇怪，我估计大家伙不会同意的

**Comment by ZeroScorpion** [comment]
如果你觉得奇怪也没办法，我只能在每行数据中增加是哪个tab的标识，然后在eSelect中对数据显示进行控制，
![image](https://user-images.githubusercontent.com/20569422/32479773-6d456272-c3c6-11e7-8c63-221d418c1103.png)但是我无法取消选中状态，不知如何是好

**Comment by TerryZ** [comment]
你的业务需求是只允许选择其中一个Tab中的数据么？

**Comment by ZeroScorpion** [comment]
是的 O(∩_∩)O~

**Comment by TerryZ** [comment]
你现在手动处理 DOM 的方式是解决不了这个问题的，选中不选中，是存放在内部对象，虽然将行 li 的 `sm_selected` 样式去掉就不会有选中的效果，但是你在 `eSelect` 的回调中，还是有那些被取中的数据返回

现有正在开发的 tab 切换回调和清空所有选中的 API 函数，组合起来使用，应该是可以完美解决你的问题的

PS：点个 `Star` 关注项目，后续也好了解项目发布信息

**Comment by ZeroScorpion** [comment]
![image](https://user-images.githubusercontent.com/20569422/32480458-f084d17e-c3c9-11e7-8d1d-1f278b2e8f3b.png)
无意发现 干掉数组中的数据能取消选中状态/(ㄒoㄒ)/~~

**Comment by TerryZ** [comment]
已增加 `eTabSwitch` 回调，用于响应多分组模式的切换
已增加 `selectMenuClear` 的 API，用于清空当前选中的项目
敬请更新 v2.0 版本
