### ISSUE TITLE
高级菜单发现的问题

### ISSUE THREAD

**Issue by ZeroScorpion** [TerryZ/SelectMenu#6]
大佬，请问我如何能刷新菜单中的值，就是我json文件变了前台如何重新生成控件。

**Comment by TerryZ** [comment]
查看官网 demo 5.1实例

**Comment by ZeroScorpion** [comment]
![image](https://user-images.githubusercontent.com/20569422/32591958-94ae77da-c55c-11e7-85a7-55b81560a8ab.png)
我这样重新请求数据的时候，数据是对的，但是 这样写没有效果

**Comment by ZeroScorpion** [comment]
大佬 有没有 qq或者微信，我想问问题哇
