### ISSUE TITLE
多分组数据下拉菜单初始化问题

### ISSUE THREAD

**Issue by EVASHINJI** [TerryZ/SelectMenu#7]
初始化只能针对没有分组的列表初始化，多组的就无法初始化了，想要下次访问页面时能保存上次选中的值

**Comment by TerryZ** [comment]
问题已收到，下个版本会修复该问题

**Comment by EVASHINJI** [comment]
还有初始化建议可以加入一个参数控制多次初始化，现在只有第一次能进行初始化，后面就没有办法刷新初始值了，非常感谢您的贡献

**Comment by TerryZ** [comment]
已在 `v2.1` 版本中修复该问题
