### ISSUE TITLE
使用SelectMenu嵌入方式的问题

### ISSUE THREAD

**Issue by TonyWang8904** [TerryZ/SelectMenu#8]
在使用嵌入方式时弹出菜单不显示，查看网页元素发现弹出菜单在绑定的div的上方，后来去除了`embed : true`选项，就能够正常显示，但是单击选项提示错误
![tim 20171205115001](https://user-images.githubusercontent.com/12045700/33589281-8162b956-d9b2-11e7-863e-d64ce19779f7.png)

**Comment by TonyWang8904** [comment]
找到报j.szie is not a function的问题了，在1364行中使用了size()方法，应该是length

**Comment by TerryZ** [comment]
你使用的 `jquery` 应该是 3.x 的版本吧？插件的开发环境是 jquery 1.x 没有使用过 3.x
